// <auto-generated />
using System;
using Herfitk.Repository.Data.DbContextBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herfitk.Repository.Data.Migrations
{
    [DbContext(typeof(HerfitkContext))]
    [Migration("20240311213627_ReCreat")]
    partial class ReCreat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Herfitk.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC279B2D105D");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("PK__Client__3214EC272790489E");

                    b.HasIndex("UserId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.ClientHerify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("Client_ID");

                    b.Property<string>("ClientReview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Client_Review");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.Property<string>("HerifyReview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Herify_Review");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Client_H__3214EC27824A65FA");

                    b.HasIndex("ClientId");

                    b.HasIndex("HerifyId");

                    b.ToTable("Client_Herify", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<string>("Zone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Herfiy__3214EC27C698B292");

                    b.HasIndex("UserId");

                    b.ToTable("Herfiy", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.HerifyCategory", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_ID");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HerifyId");

                    b.ToTable("Herify_Category", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.Property<string>("PaymentTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Payment_term");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3214EC2751EE6894");

                    b.HasIndex("HerifyId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC27D1EB7E98");

                    b.HasIndex("UserId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("Hire_Date");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int?>("WorkHours")
                        .HasColumnType("int")
                        .HasColumnName("Work_Hours");

                    b.HasKey("Id")
                        .HasName("PK__Staff__3214EC27832438F9");

                    b.HasIndex("UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Herfitk.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Account_State");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("National_ID");

                    b.Property<string>("NationalIdImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NationalID_Image");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalImage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Personal_Image");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC272A074D8C");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Client", b =>
                {
                    b.HasOne("Herfitk.Models.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Client__User_ID__3F466844");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herfitk.Models.ClientHerify", b =>
                {
                    b.HasOne("Herfitk.Models.Client", "Client")
                        .WithMany("ClientHerifies")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK__Client_He__Clien__4CA06362");

                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany("ClientHerifies")
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Client_He__Herif__4D94879B");

                    b.Navigation("Client");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.HasOne("Herfitk.Models.User", "User")
                        .WithMany("Herfiys")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Herfiy__User_ID__4222D4EF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herfitk.Models.HerifyCategory", b =>
                {
                    b.HasOne("Herfitk.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Herify_Ca__Categ__49C3F6B7");

                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany()
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Herify_Ca__Herif__48CFD27E");

                    b.Navigation("Category");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Payment", b =>
                {
                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany("Payments")
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Payment__Herify___46E78A0C");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Role", b =>
                {
                    b.HasOne("Herfitk.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Role__User_ID__398D8EEE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herfitk.Models.Staff", b =>
                {
                    b.HasOne("Herfitk.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Staff__User_ID__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herfitk.Models.Client", b =>
                {
                    b.Navigation("ClientHerifies");
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.Navigation("ClientHerifies");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Herfitk.Models.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Herfiys");

                    b.Navigation("Roles");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
