// <auto-generated />
using System;
using Herfitk.Repository.Data.DbContextBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herfitk.Repository.Data.Migrations
{
    [DbContext(typeof(HerfitkContext))]
    [Migration("20240313075049_TestIntegrate")]
    partial class TestIntegrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Herfitk.Core.Models.HerifyAppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIdImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Herfitk.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC279B2D105D");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("PK__Client__3214EC272790489E");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.ClientHerify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("Client_ID");

                    b.Property<string>("ClientReview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Client_Review");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.Property<string>("HerifyReview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Herify_Review");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Client_H__3214EC27824A65FA");

                    b.HasIndex("ClientId");

                    b.HasIndex("HerifyId");

                    b.ToTable("Client_Herify", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HerfiyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("User_ID");

                    b.Property<string>("Zone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Herfiy__3214EC27C698B292");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Herfiy", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.HerifyCategory", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_ID");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HerifyId");

                    b.ToTable("Herify_Category", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("HerifyId")
                        .HasColumnType("int")
                        .HasColumnName("Herify_ID");

                    b.Property<string>("PaymentTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Payment_term");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Payment__3214EC2751EE6894");

                    b.HasIndex("HerifyId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC27D1EB7E98");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Herfitk.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("Hire_Date");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int?>("WorkHours")
                        .HasColumnType("int")
                        .HasColumnName("Work_Hours");

                    b.HasKey("Id")
                        .HasName("PK__Staff__3214EC27832438F9");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Herfitk.Models.ClientHerify", b =>
                {
                    b.HasOne("Herfitk.Models.Client", "Client")
                        .WithMany("ClientHerifies")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK__Client_He__Clien__4CA06362");

                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany("ClientHerifies")
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Client_He__Herif__4D94879B");

                    b.Navigation("Client");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.HasOne("Herfitk.Core.Models.HerifyAppUser", "User")
                        .WithOne()
                        .HasForeignKey("Herfitk.Models.Herfiy", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Herfitk.Models.HerifyCategory", b =>
                {
                    b.HasOne("Herfitk.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Herify_Ca__Categ__49C3F6B7");

                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany()
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Herify_Ca__Herif__48CFD27E");

                    b.Navigation("Category");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Payment", b =>
                {
                    b.HasOne("Herfitk.Models.Herfiy", "Herify")
                        .WithMany("Payments")
                        .HasForeignKey("HerifyId")
                        .HasConstraintName("FK__Payment__Herify___46E78A0C");

                    b.Navigation("Herify");
                });

            modelBuilder.Entity("Herfitk.Models.Client", b =>
                {
                    b.Navigation("ClientHerifies");
                });

            modelBuilder.Entity("Herfitk.Models.Herfiy", b =>
                {
                    b.Navigation("ClientHerifies");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
